In [1]:
import numpy as np
import matplotlib.pyplot as plt
import math
%matplotlib inline
import random


In [2]:
import sys
sys.path
sys.path.insert(0, '/Users/asaadeldin/Downloads/GitHub/graspy')

In [3]:
from graspy.match import SeededGraphMatching as SGM

In [4]:
def SGMtest2(A,B,pi):
    n = A.shape[0]
    for m in range(n-2,n):
        ofvs = [0]*30
        for i in range(30):
            W1 = np.sort(random.sample(list(range(n)),10))
            W2 = np.array([pi[z] for z in W1])
            faq = SGM(n_init=100,init_method="rand",shuffle_input=False)
            faq = faq.fit(A,B,W1,W2)
            ofvs[i] = faq.score_
        print(np.mean(ofvs))

In [9]:
with open("qapdata/chr12c.dat") as f:
    f = [int(elem) for elem in f.read().split()]
# adjusting
f = np.array(f[1:])
n = int(math.sqrt(len(f) / 2))
f = f.reshape(2 * n, n)
A = f[:n, :]
B = f[n:, :]
pi = np.array([7,5,1,3,10,4,8,6,9,11,2,12])-[1]*n
W1 = np.sort(random.sample(list(range(n)),3))
W2 = np.array([pi[z] for z in W1])
faq = SGM(n_init=100,init_method="rand",shuffle_input=False)
faq = faq.fit(A,B,W1,W2)
#SGMtest2(A,B,pi)


In [10]:
print(W1)
print(W2)
print(pi)
print(faq.perm_inds_)
print(faq.score_)
print(np.trace(np.transpose(A) @ B[np.ix_(faq.perm_inds_, faq.perm_inds_)]))

[0 3 5]
[6 2 3]
[ 6  4  0  2  9  3  7  5  8 10  1 11]
[ 6  4  0  2  9  3  7  5  8 10  1 11]
11156
11156


In [7]:
pi = np.array([7,5,1,3,10,4,8,6,9,11,2,12])-[1]*n
W1 = np.sort(random.sample(list(range(n)),2))
W2 = np.array([pi[z] for z in W1])
print(W1)
print(W2)

[0 3]
[6 2]


In [8]:
pi = np.array([7,5,1,3,10,4,8,6,9,11,2,12])-[1]*n
W1 = np.sort(random.sample(list(range(n)),10))
W1 = W1.reshape(10,1)

W2 = np.array([pi[z] for z in W1])
W2 = W2.reshape(10,1)
print(W1.shape)
print(np.array([x for x in range(n) if x not in W1]).shape)
#p_A = np.concatenate([W1,np.array([x for x in range(n) if x not in W1])],axis=None)
p_A = np.concatenate([W1, np.array([x for x in range(n) if x not in W1])],axis=None)
p_B = np.concatenate([W2, np.array([x for x in range(n) if x not in W2])],axis=None)
print(A)
A = A[np.ix_(p_A, p_A)]
print(A)
print(W1)
print(p_A)
print(p_B)
faq = SGM(n_init=100,init_method="rand",shuffle_input=False)
faq = faq.fit(A,B,W1,W2)
W1 = W1.reshape(10,)
print(W1)

(10, 1)
(2,)
[[ 0 90 10  0  0  0  0  0  0  0  0  0]
 [90  0  0 23  0  0  0  0  0  0  0  0]
 [10  0  0  0 43  0  0  0  0  0  0  0]
 [ 0 23  0  0  0 88  0  0  0  0  0  0]
 [ 0  0 43  0  0  0 26  0  0  0  0  0]
 [ 0  0  0 88  0  0  0 16  0  0  0  0]
 [ 0  0  0  0 26  0  0  0  1  0  0  0]
 [ 0  0  0  0  0 16  0  0  0 96  0  0]
 [ 0  0  0  0  0  0  1  0  0  0 29  0]
 [ 0  0  0  0  0  0  0 96  0  0  0 37]
 [ 0  0  0  0  0  0  0  0 29  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 37  0  0]]
[[ 0 90 10  0  0  0  0  0  0  0  0  0]
 [90  0  0 23  0  0  0  0  0  0  0  0]
 [10  0  0  0 43  0  0  0  0  0  0  0]
 [ 0 23  0  0  0  0  0  0  0  0 88  0]
 [ 0  0 43  0  0 26  0  0  0  0  0  0]
 [ 0  0  0  0 26  0  0  1  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 16 96]
 [ 0  0  0  0  0  1  0  0 29  0  0  0]
 [ 0  0  0  0  0  0  0 29  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 37]
 [ 0  0  0 88  0  0 16  0  0  0  0  0]
 [ 0  0  0  0  0  0 96  0  0 37  0  0]]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 6]
 [ 7]
 [ 8]
 

In [9]:
x = np.arange(4)
xx = x.reshape(4,1)
y = np.ones(5)
print(xx)
print(y)
print(xx+y)

[[0]
 [1]
 [2]
 [3]]
[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]


In [10]:
import numpy as np
import math
from scipy.optimize import linear_sum_assignment
from scipy.optimize import minimize_scalar
from sklearn.utils import check_array
from graspy.match import SinkhornKnopp


class SGM1:
    """
    Seeded Graph Matching Algorithm (SGM)
    The seeded graph matching problem is a variation of graph matching
     in which part of the matching is fixed. This algorithm is a modification
     of FAQ, an algorithm also implemented in this package[1].


    Parameters
    ----------

    n_init : int, positive (default = 1)
        Number of random initializations of the starting permutation matrix that
        the FAQ algorithm will undergo. n_init automatically set to 1 if
        init_method = 'barycenter'

    init_method : string (default = 'barycenter')
        The initial position chosen

        "barycenter" : the non-informative “flat doubly stochastic matrix,”
        :math:`J=1*1^T /n` , i.e the barycenter of the feasible region

        "rand" : some random point near :math:`J, (J+K)/2`, where K is some random doubly
        stochastic matrix

    max_iter : int, positive (default = 30)
        Integer specifying the max number of FW iterations.
        FAQ typically converges with modest number of iterations

    shuffle_input : bool (default = True)
        Gives users the option to shuffle the nodes of A matrix to avoid results
        from inputs that were already matched

    eps : float (default = 0.1)
        A positive, threshold stopping criteria such that FW continues to iterate
        while Frobenius norm of :math:`(P_{i}-P_{i+1}) > eps`


    gmp : bool (default = False)
        Gives users the option to the Graph Matching Problem (GMP) rather than
        the Quadratic Assignment (QAP). This is accomplished through trivial
        negation of the objective function.

    Attributes
    ----------

    perm_inds_ : array, size (n,) where n is the number of vertices in the graphs fitted.
        The indices of the optimal permutation on the nodes of B, found via
        FAQ, to best minimize the objective function :math:`f(P) = trace(A^T PBP^T )`.


    score_ : float
        The objective function value of for the optimal permutation found.


    References
    ----------
    .. [1] J. T. Vogelstein, J. M. Conroy, V. Lyzinski, L. J. Podrazik, S. G. Kratzer,
           E. T. Harley, D. E. Fishkind, R. J. Vogelstein, and C. E. Priebe, “Fast
           approximate quadratic programming for graph matching,” PLOS one, vol. 10,
           no. 4, p. e0121002, 2015.



    """

    def __init__(
        self,
        n_init=1,
        init_method="barycenter",
        max_iter=30,
        shuffle_input=True,
        eps=0.1,
        gmp=False,
    ):

        if n_init > 0 and type(n_init) is int:
            self.n_init = n_init
        else:
            msg = '"n_init" must be a positive integer'
            raise TypeError(msg)
        if init_method == "rand":
            self.init_method = "rand"
        elif init_method == "barycenter":
            self.init_method = "barycenter"
            self.n_init = 1
        else:
            msg = 'Invalid "init_method" parameter string'
            raise ValueError(msg)
        if max_iter > 0 and type(max_iter) is int:
            self.max_iter = max_iter
        else:
            msg = '"max_iter" must be a positive integer'
            raise TypeError(msg)
        if type(shuffle_input) is bool:
            self.shuffle_input = shuffle_input
        else:
            msg = '"shuffle_input" must be a boolean'
            raise TypeError(msg)
        if eps > 0 and type(eps) is float:
            self.eps = eps
        else:
            msg = '"eps" must be a positive float'
            raise TypeError(msg)
        if type(gmp) is bool:
            self.gmp = gmp
        else:
            msg = '"gmp" must be a boolean'
            raise TypeError(msg)

    def fit(self, A, B, W1, W2):
        """
        Fits the model with two assigned adjacency matrices

        Parameters
        ---------
        A : 2d-array, square, positive
            A square, positive adjacency matrix

        B : 2d-array, square, positive
            A square, positive adjacency matrix

        W1 : 1d-array, shape (m , 1) where m <= n
            An array where each entry is a node in A

        W2 : 1d-array, shape (m , 1) where m <= n
            An array where each entry is a node in B
            The elements of W1 and W2 are seeds, creating a fixed
            seeding of W1 -> W2

        Returns
        -------

        self : returns an instance of self
        """
        A = check_array(A, copy=True, ensure_2d=True)
        B = check_array(B, copy=True, ensure_2d=True)

        if A.shape[0] != B.shape[0]:
            msg = "Adjacency matrices must be of equal size"
            raise ValueError(msg)
        elif A.shape[0] != A.shape[1] or B.shape[0] != B.shape[1]:
            msg = "Adjacency matrix entries must be square"
            raise ValueError(msg)
        elif (A >= 0).all() == False or (B >= 0).all() == False:
            msg = "Adjacency matrix entries must be greater than or equal to zero"
            raise ValueError(msg)
        elif W1.shape[0] != W2.shape[0]:
            msg = "Seed arrays must be of equal size"
            raise ValueError(msg)
        elif W1.shape[0] > A.shape[0]:
            msg = "There cannot be more seeds than there are nodes"
            raise ValueError(msg)
        elif (W1 >= 0).all() == False or (W2 >= 0).all() == False:
            msg = "Seed array entries must be greater than or equal to zero"
            raise ValueError(msg)

        n = A.shape[0]  # number of vertices in graphs
        n_seeds = W1.shape[0]  # number of seeds
        n_unseed = n - n_seeds

        obj_func_scalar = 1
        if self.gmp:
            obj_func_scalar = -1
        W1_c = np.array([x for x in range(n) if x not in W1])
        W2_c = np.array([x for x in range(n) if x not in W2])
        p_A = np.concatenate(
            [W1, W1_c], axis=None
        )
        p_B = np.concatenate(
            [W2, W2_c], axis=None
        )
        A = A[np.ix_(p_A, p_A)]
        B = B[np.ix_(p_B, p_B)]
        if self.shuffle_input:
            node_shuffle_input = np.concatenate(
                (np.arange(n_seeds), np.random.permutation(np.arange(n_seeds, n)))
            )
        
            A = A[np.ix_(node_shuffle_input, node_shuffle_input)]
            # shuffle_input to avoid results from inputs that were already matched

        A11 = A[:n_seeds, :n_seeds]
        A12 = A[:n_seeds, n_seeds:]
        A21 = A[n_seeds:, :n_seeds]
        A22 = A[n_seeds:, n_seeds:]
        B11 = B[:n_seeds, :n_seeds]
        B12 = B[:n_seeds, n_seeds:]
        B21 = B[n_seeds:, :n_seeds]
        B22 = B[n_seeds:, n_seeds:]
        A11T = np.transpose(A11)
        A12T = np.transpose(A12)
        A22T = np.transpose(A22)
        B21T = np.transpose(B21)
        B22T = np.transpose(B22)

        score = math.inf
        perm_inds = np.zeros(n)

        for i in range(self.n_init):

            # setting initialization matrix
            if self.init_method == "rand":
                sk = SinkhornKnopp()
                K = np.random.rand(
                    n - n_seeds, n - n_seeds
                )  # generate a nxn matrix where each entry is a random integer [0,1]
                for i in range(10):  # perform 10 iterations of Sinkhorn balancing
                    K = sk.fit(K)
                J = np.ones((n - n_seeds, n - n_seeds)) / float(
                    n - n_seeds
                )  # initialize J, a doubly stochastic barycenter
                P = (K + J) / 2
            elif self.init_method == "barycenter":
                P = np.ones((n - n_seeds, n - n_seeds)) / float(n - n_seeds)

            const_sum = A21 @ np.transpose(B21) + np.transpose(A12) @ B12
            grad_P = math.inf  # gradient of P
            n_iter = 0  # number of FW iterations

            # OPTIMIZATION WHILE LOOP BEGINS
            while grad_P > self.eps and n_iter < self.max_iter:
                delta_f = (
                    const_sum + A22 @ P @ B22T + A22T @ P @ B22
                )  # computing the gradient of f(P) = -tr(APB^tP^t)
                rows, cols = linear_sum_assignment(
                    obj_func_scalar * delta_f
                )  # run hungarian algorithm on gradient(f(P))
                Q = np.zeros((n_unseed, n_unseed))
                Q[rows, cols] = 1  # initialize search direction matrix Q

                def f(x):  # computing the original optimization function
                    return obj_func_scalar * np.trace(A11T@B11) + np.trace(np.transpose(x*P+(1-x)*Q)@A21@B21T) + np.trace(np.transpose(x*P+(1-x)*Q)@A12T@B12) + np.trace(A22T@(x*P+(1-x)*Q)@B22@np.transpose(x*P+(1-x)*Q)) 

                alpha = minimize_scalar(
                    f, bounds=(0, 1), method="bounded"
                ).x  # computing the step size
                P_i1 = alpha * P + (1 - alpha) * Q  # Update P
                grad_P = np.linalg.norm(P - P_i1)
                P = P_i1
                n_iter += 1
            # end of FW optimization loop

            row, col = linear_sum_assignment(
                -P
            )  # Project onto the set of permutation matrices
            
            perm_inds_new = np.concatenate(
                (np.arange(n_seeds), np.array([x + n_seeds for x in col]))
            )
            
            score_new = np.trace(
                np.transpose(A) @ B[np.ix_(perm_inds_new, perm_inds_new)]
            )  # computing objective function value

            if obj_func_scalar * score_new < obj_func_scalar * score:  # minimizing
                score = score_new
                if self.shuffle_input:
                    perm_inds = np.array([0] * n)
                    perm_inds[node_shuffle_input] = perm_inds_new
                    perm_inds[p_A] = perm_inds
                    
                else:
                    
                    perm_inds = np.array([0] * n)
                    perm_inds[W1] = W2
                    perm_inds[W1_c] = W2_c[col]
                    perm_inds = perm_inds.astype(int)

        if self.shuffle_input:
            node_unshuffle_input = np.array(range(n))
            node_unshuffle_input[node_shuffle_input] = np.array(range(n))
            A = A[np.ix_(node_unshuffle_input, node_unshuffle_input)]
            score = np.trace(np.transpose(A) @ B[np.ix_(perm_inds, perm_inds)])

        p_A_unshuffle = np.array(range(n))
        p_A_unshuffle[p_A] = np.array(range(n))
        A = A[np.ix_(p_A_unshuffle, p_A_unshuffle)]
        p_B_unshuffle = np.array(range(n))
        p_B_unshuffle[p_B] = np.array(range(n))
        B = B[np.ix_(p_B_unshuffle, p_B_unshuffle)]
        score = np.trace(np.transpose(A) @ B[np.ix_(perm_inds, perm_inds)])
        
        self.perm_inds_ = perm_inds  # permutation indices
        self.score_ = score  # objective function value
        return self

    def fit_predict(self, A, B):
        """
        Fits the model with two assigned adjacency matrices, returning optimal
        permutation indices

        Parameters
        ---------
        A : 2d-array, square, positive
            A square, positive adjacency matrix

        B : 2d-array, square, positive
            A square, positive adjacency matrix

        Returns
        -------

        perm_inds_ : 1-d array, some shuffling of [0, n_vert)
            The optimal permutation indices to minimize the objective function
        """
        self.fit(A, B)
        return self.perm_inds_

In [ ]:
with open("qapdata/chr12c.dat") as f:
    f = [int(elem) for elem in f.read().split()]
# adjusting
f = np.array(f[1:])
n = int(math.sqrt(len(f) / 2))
f = f.reshape(2 * n, n)
A = f[:n, :]
B = f[n:, :]
pi = np.array([7,5,1,3,10,4,8,6,9,11,2,12])-[1]*n

W1 = np.sort(random.sample(list(range(n)),3))
#W1 = np.array([3, 5, 9])
W2 = np.array([pi[z] for z in W1])
faq = SGM1(n_init=100,init_method="rand",shuffle_input=False)
faq = faq.fit(A,B,W1,W2)



In [ ]:
print(W1)
print(W2)
print(pi)
print(faq.perm_inds_)
print(faq.score_)
print(np.trace(np.transpose(A) @ B[np.ix_(faq.perm_inds_, faq.perm_inds_)]))


In [ ]:
# Install a conda package in the current Jupyter kernel
import sys
!conda install --yes --prefix {sys.prefix} numpy

In [ ]:
!type python


In [ ]:
sys.executable

In [ ]:
# Install a pip package in the current Jupyter kernel
import sys
!{sys.executable} -m pip install numpy